name: ReviewDoc
on:
  push:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2


      - name: Install Latex
        run: |
          sudo apt-get install texlive texlive-lang-german texlive-latex-extra 
          sudo apt-get install texlive-base 

      - name: Where am I 
        run: |
          pwd
          ls -a

      - name: Compile LaTeX document
        run: |
          cd ./ReviewDoc/
          pdflatex -synctex=1 -interaction=nonstopmode "ReviewDoc.tex" 
          makeindex -s nomencl.ist -o ReviewDoc.nls ReviewDoc.nlo
          pdflatex -synctex=1 -interaction=nonstopmode "ReviewDoc.tex" 
          cd ..       
          cp ./ReviewDoc/ReviewDoc.pdf ./ReviewDoc.pdf

      - name: Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: ./ReviewDoc/ReviewDoc.pdf

      - name: Clean Git
        run: |
          git clean -fX 
