name: Sprintlog_Riffecs_1
on:
  push:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Where am I 
        run: |
          pwd
          ls -a

      - name: Install Latex
        run: |
          sudo apt-get install texlive texlive-lang-german texlive-latex-extra 
          sudo apt-get install texlive-base 

      - name: Overleaf
        run: sudo apt-get texlive-olplainarticle

      - name: Compile LaTeX document
        run: |
          cd ./Sprintbacklog/Riffecs
          pdflatex -synctex=1 -interaction=nonstopmode "Riffecs_Backlog1.tex" 
          makeindex -s nomencl.ist -o Riffecs_Backlog1.nls Riffecs_Backlog1.nlo
          pdflatex -synctex=1 -interaction=nonstopmode "Riffecs_Backlog1.tex" 
          cd ..       
          cp ./Sprintbacklog/Riffecs/Riffecs_Backlog1.pdf ./Backlog_1_Riffecs.pdf

      - name: Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: ./Backlog_1_Riffecs.pdf

      - name: X-FAB Upload
        run: |
          python upload.py ./Backlog_1_Riffecs.pdf
        env:
          key: ${{ secrets.FTP_PASSWORD }}
          user: ${{ secrets.FTP_USER }}
          server: ${{ secrets.FTP_SERVER }}

      - name: Clean Git
        run: |
          git clean -fX 